// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipes.Persistance;

#nullable disable

namespace Recipes.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Recipes.Domain.Entities.RecipeCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecipeCards", (string)null);
                });

            modelBuilder.Entity("Recipes.Domain.Entities.RecipeCardDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CookingProcess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeCardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCardId")
                        .IsUnique();

                    b.ToTable("RecipeCardDetails", (string)null);
                });

            modelBuilder.Entity("Recipes.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Recipes.Domain.Entities.RecipeCard", b =>
                {
                    b.OwnsOne("Recipes.Domain.ValueObjects.RecipeMainImage", "Image", b1 =>
                        {
                            b1.Property<int>("RecipeCardId")
                                .HasColumnType("int")
                                .HasColumnName("RecipeCardId");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Content");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContentType");

                            b1.Property<string>("FileName")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FileName");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("Size");

                            b1.HasKey("RecipeCardId");

                            b1.ToTable("RecipeMainImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeCardId");
                        });

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("Recipes.Domain.Entities.RecipeCardDetails", b =>
                {
                    b.HasOne("Recipes.Domain.Entities.RecipeCard", null)
                        .WithOne("Details")
                        .HasForeignKey("Recipes.Domain.Entities.RecipeCardDetails", "RecipeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Recipes.Domain.ValueObjects.Hashtag", "Hashtags", b1 =>
                        {
                            b1.Property<int>("RecipeCardDetailsId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Title");

                            b1.HasKey("RecipeCardDetailsId", "Id");

                            b1.HasIndex("Title");

                            b1.ToTable("Hashtags");

                            b1.WithOwner()
                                .HasForeignKey("RecipeCardDetailsId");
                        });

                    b.OwnsMany("Recipes.Domain.ValueObjects.Ingredient", "Ingredients", b1 =>
                        {
                            b1.Property<int>("RecipeCardDetailsId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Name");

                            b1.Property<string>("Quantity")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Quantity");

                            b1.HasKey("RecipeCardDetailsId", "Id");

                            b1.HasIndex("Name");

                            b1.ToTable("Ingredients", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeCardDetailsId");
                        });

                    b.Navigation("Hashtags");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Recipes.Domain.Entities.RecipeCard", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
