version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5000:80"
    depends_on:
        - database
  database:
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Tima22282SqlServer
  client:
    ports:
      - "5001:3000"
  proxy:
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80" 
